export const SKILLS = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Go",
  "Rust",
  "Ruby",
  "Swift",
  "Kotlin",
  "Next.js",
  "React",
  "Vue",
  "Nuxt",
  "Svelte",
  "Astro",
  "Remix",
  "FastAPI",
  "Django",
  "Flask",
  "Rails",
  "Express",
  "NestJS",
  "OpenAI API",
  "Anthropic API",
  "Gemini API",
  "LangChain",
  "LlamaIndex",
  "LangGraph",
  "Vercel AI SDK",
  "Mastra",
  "Pinecone",
  "Weaviate",
  "Qdrant",
  "Supabase Vector",
  "PGVector",
  "Chroma",
  "LangFuse",
  "LangSmith",
  "AWS",
  "GCP",
  "Azure",
  "Vercel",
  "Cloudflare",
  "Supabase",
  "Firebase",
  "Docker",
  "Kubernetes",
  "Bedrock",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "BigQuery",
  "Stripe",
  "Twilio",
  "Slack API",
  "Notion API",
  "Salesforce API",
  "kintone",
] as const;

export const AI_SPECIALTIES = [
  "LLMアプリ開発",
  "RAGシステム",
  "AIエージェント",
  "Fine-tuning",
  "プロンプトエンジニアリング",
  "音声AI（TTS/STT）",
  "画像生成AI",
  "動画生成AI",
  "MLOps",
  "評価・監視（LangSmith / LangFuse）",
  "Vector DB / Embedding",
  "マルチモーダル",
  "AI運用・モニタリング",
  "コスト最適化",
  "モデル選定・ベンチマーク",
] as const;

export const INDUSTRIES = [
  "finance",
  "healthcare",
  "legal",
  "real_estate",
  "retail",
  "manufacturing",
  "hr",
  "education",
  "media",
  "other",
] as const;

export const INDUSTRY_LABELS: Record<(typeof INDUSTRIES)[number], string> = {
  finance: "金融",
  healthcare: "医療",
  legal: "法律",
  real_estate: "不動産",
  retail: "小売",
  manufacturing: "製造",
  hr: "人材",
  education: "教育",
  media: "メディア",
  other: "その他",
};
